language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r erpteam-stury *
  - mkdir -p deploy
  - mv erpteam-stury.zip deploy/erpteam-stury.zip

deploy:
  - provider: s3
    access_key_id: AKIAR35EP2CGCOM5UQT4 # Travis repo settings에 설정된 값
    secret_access_key: msaEOPSQrG9FA10G2hij+gI8J9YZH3meaKtzMDiI # Travis repo settings에 설정된 값
    bucket: tw-test-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true


  - provider: codedeploy
    access_key_id: AKIAR35EP2CGCOM5UQT4
    secret_access_key: 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

    key: erpteam-stury.zip
    bucket: tw-test-build


    bundle_type: zip
    application: erpteam-stury
    deployment_group: erpteam-stury-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - omrcard88@gmail.com